### PR TITLE
Fixed Tests Errors

### PR DESCRIPTION
**Pull request by alkhatib**
Including "conditions" folder from tracecompass.TMF

### CODE REVIEW

**Comment by sshahriyar** [comment]
Your patch doesn't compile using Maven.  The build failed! If you want to contribute a patch, then you need to make sure it compiles using Maven. Thanks.

**Comment by alkhatib** [comment]
The failure is unrelated to my patch, it is because the nightly repo for Trace compass is no longer available.

```
[ERROR] Internal error: java.lang.RuntimeException: Failed to resolve target definition /home/travis/build/sshahriyar/totalads/org.eclipse.tracecompass.totalads.target/totalads-4.4.target: Failed to load p2 metadata repository from location http://download.eclipse.org/tracecompass/master/nightly: No repository found at http://download.eclipse.org/tracecompass/master/nightly. -> [Help 1]
```

I'll submit another commit that fixes that.

**Comment by alkhatib** [comment]
It passes now, and I'm actually wondering how the previous commits  in the repo passed the tests with those missing files.

**Comment by ghost** [comment]
> The failure is unrelated to my patch, it is because the nightly repo for Trace compass is no longer available.

The Trace Compass "nightly" update site was recently moved to:
http://download.eclipse.org/tracecompass/master/repository/

**Comment by sshahriyar** [comment]
Thanks Alex and Alkhatib

**Pull request merged**
