### PR TITLE
Fix compilation by depending on a specific version (0.1.0) of Trace Compass

### PR DESCRIPTION
**Pull request by ghost**
and other miscellaneous fixes

### CODE REVIEW

**Comment by ghost** [comment]
I would also suggest to merge "master" into the "develop" branch, because most people will just try to build master without reading the README, and it will fail ;)

**Comment by sshahriyar** [comment]
Okay, thanks for the commit and resolvign the issue. I have incorporated your changes and merged develop into master as well as staging.

**Comment by sshahriyar** [comment]
There is a bug in compilation of Maven. It is compiling only via Eclipse. See below:

[ERROR]   Missing requirement: org.eclipse.tracecompass.totalads.feature.group 0.1.0.qualifier requires 'org.eclipse.license.feature.group 0.0.0' but it could not be found

Could you please fix this?

**Comment by ghost** [comment]
The license feature is now part of its own update site. You need to add that separately. PR https://github.com/sshahriyar/totalads/pull/4 should fix it.

**Pull request merged**
